### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by padevin** [brianleect/binance-pump-alerts#75]
Traceback (most recent call last):
  File "c:\Users\ismai\Desktop\projeyusuf\binance-pump-alerts-master\binance-pump-alerts-master\pumpAlerts.py", line 7, in <module>
    from sender import TelegramSender
  File "c:\Users\ismai\Desktop\projeyusuf\binance-pump-alerts-master\binance-pump-alerts-master\sender\__init__.py", line 1, in <module>
    from .TelegramSender import TelegramSender
  File "c:\Users\ismai\Desktop\projeyusuf\binance-pump-alerts-master\binance-pump-alerts-master\sender\TelegramSender.py", line 4, in <module>
    from telegram import Bot, ParseMode
ImportError: cannot import name 'ParseMode' from 'telegram' (C:\Python311\Lib\site-packages\telegram\__init__.py)

**Comment by brianleect** [comment]
Thanks for the issue, I suspect it might be a breaking change due to a version upgrade by python-telegram-bot , let me investigate further once I've time ideally sometime today or later tmr

**Comment by brianleect** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/issues/3005 Seems linked to.

**Comment by brianleect** [comment]
https://github.com/brianleect/binance-pump-alerts/commit/7237bd55a58910d8f61799023fbb7629a25567fa

Fixed. @padevin 

Specified python-telegram-version to use an older version so it should function now. Closing. Lmk if it doesn't fix the problem.

**Comment by padevin** [comment]
worked thanks
