### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by padevin** [brianleect/binance-pump-alerts#77]
```
Traceback (most recent call last):
  File "c:\Users\yusufarsln342\Desktop\projeyusuf\projeyusuf\binance-pump-alerts-masternew\binance-pump-alerts-master\pumpAlerts.py", line 92, in <module>
    main()
  File "c:\Users\yusufarsln342\Desktop\projeyusuf\projeyusuf\binance-pump-alerts-masternew\binance-pump-alerts-master\pumpAlerts.py", line 64, in main
    alerter = BinancePumpAndDumpAlerter(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\yusufarsln342\Desktop\projeyusuf\projeyusuf\binance-pump-alerts-masternew\binance-pump-alerts-master\alerter\BinancePumpAndDumpAlerter.py", line 62, in __init__
    ] = ConversionUtils.duration_to_seconds(interval)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\yusufarsln342\Desktop\projeyusuf\projeyusuf\binance-pump-alerts-masternew\binance-pump-alerts-master\utils\ConversionUtils.py", line 12, in duration_to_seconds
    return int(duration[:-1]) * unit
           ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '30m'
```

**Comment by brianleect** [comment]
Is this issue occurring for your google VM environment only or both your laptop and google VM? Perhaps you could try running it on a ec2 instance?
